# Generated by Django 4.2.27 on 2026-01-02 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'idempotency_keys',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('wallet', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
                'indexes': [models.Index(fields=['telegram_id'], name='user_profil_telegra_167c81_idx'), models.Index(fields=['wallet'], name='user_profil_wallet_d5eb01_idx')],
            },
        ),
        migrations.CreateModel(
            name='TonProofPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(db_index=True, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ton_proof_payloads',
                'indexes': [models.Index(fields=['payload'], name='ton_proof_p_payload_9e0ab6_idx'), models.Index(fields=['expires_at'], name='ton_proof_p_expires_0c63db_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RATE_LIMIT', 'RATE_LIMIT'), ('DUP_TX', 'DUP_TX'), ('WALLET_REUSED', 'WALLET_REUSED'), ('ACTIVE_CYCLE', 'ACTIVE_CYCLE'), ('REF_LIMIT', 'REF_LIMIT'), ('SELF_REFERRAL', 'SELF_REFERRAL'), ('BAD_TX', 'BAD_TX')], db_index=True, max_length=32)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to='api.userprofile')),
            ],
            options={
                'db_table': 'risk_events',
                'indexes': [models.Index(fields=['kind', 'created_at'], name='risk_events_kind_9df67e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('SENT', 'SENT')], db_index=True, default='REQUESTED', max_length=16)),
                ('tx_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='api.userprofile')),
            ],
            options={
                'db_table': 'payout_requests',
                'indexes': [models.Index(fields=['user', 'status'], name='payout_requ_user_id_3458b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_code', models.CharField(blank=True, max_length=32, null=True)),
                ('tx_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], db_index=True, default='NEW', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='api.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='api.userprofile')),
            ],
            options={
                'db_table': 'participations',
                'indexes': [models.Index(fields=['user', 'status'], name='participati_user_id_02d1f0_idx'), models.Index(fields=['referrer', 'status'], name='participati_referre_8c561e_idx'), models.Index(fields=['referrer', 'created_at'], name='participati_referre_41b813_idx'), models.Index(fields=['tx_hash'], name='participati_tx_hash_a1582f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_codes', to='api.userprofile')),
            ],
            options={
                'db_table': 'author_codes',
                'indexes': [models.Index(fields=['code'], name='author_code_code_c045e9_idx')],
            },
        ),
    ]
