# Generated by Django 4.2.27 on 2025-12-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TonProofPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(db_index=True, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ton_proof_payloads',
                'indexes': [models.Index(fields=['payload'], name='ton_proof_p_payload_9e0ab6_idx'), models.Index(fields=['expires_at'], name='ton_proof_p_expires_0c63db_idx')],
            },
        ),
    ]
