# Generated by Django 4.2.27 on 2026-01-04 22:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('wallet_address', models.CharField(blank=True, default='', max_length=128)),
                ('amount_nano', models.BigIntegerField()),
                ('comment', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_event_id', models.CharField(blank=True, default='', max_length=128)),
                ('paid_tx_hash', models.CharField(blank=True, default='', max_length=128)),
                ('participation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to='api.participation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='api.userprofile')),
            ],
            options={
                'db_table': 'payment_orders',
                'indexes': [models.Index(fields=['public_id'], name='payment_ord_public__d9aa64_idx'), models.Index(fields=['status'], name='payment_ord_status_2f0277_idx'), models.Index(fields=['wallet_address'], name='payment_ord_wallet__c8b2f2_idx'), models.Index(fields=['created_at'], name='payment_ord_created_57a748_idx')],
            },
        ),
    ]
