# Generated by Django 4.2.27 on 2025-12-28 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tonproofpayload'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='author_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='author_code_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invited_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inviter_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inviter_telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inviter_wallet_address',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='participation_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('COMPLETED', 'COMPLETED'), ('BLOCKED', 'BLOCKED')], db_index=True, default='NEW', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payouts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_points', models.IntegerField()),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('APPROVED', 'APPROVED'), ('PAID', 'PAID'), ('REJECTED', 'REJECTED')], db_index=True, default='REQUESTED', max_length=16)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='api.userprofile')),
            ],
            options={
                'db_table': 'payout_requests',
                'indexes': [models.Index(fields=['user', 'status'], name='payout_requ_user_id_3458b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd_cents', models.IntegerField(default=1500)),
                ('amount_nanotons', models.CharField(max_length=32)),
                ('receiver_wallet', models.CharField(max_length=128)),
                ('comment', models.CharField(db_index=True, max_length=128, unique=True)),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('PENDING_REVIEW', 'PENDING_REVIEW'), ('CONFIRMED', 'CONFIRMED'), ('FAILED', 'FAILED')], db_index=True, default='CREATED', max_length=20)),
                ('tx_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.userprofile')),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['user', 'status'], name='payments_user_id_1b771c_idx'), models.Index(fields=['comment'], name='payments_comment_cff5dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'login'), ('connect', 'connect'), ('telegram_verify', 'telegram_verify'), ('apply_code', 'apply_code'), ('inviter_set', 'inviter_set'), ('payment_create', 'payment_create'), ('payment_confirm', 'payment_confirm')], db_index=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.userprofile')),
            ],
            options={
                'db_table': 'event_logs',
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='event_logs_event_t_f0df7d_idx')],
            },
        ),
    ]
