# Generated by Django 4.2.27 on 2026-01-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_author_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'author_codes',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd_cents', models.IntegerField(default=1500)),
                ('tx_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], db_index=True, default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'participations',
            },
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(fields=('telegram_id',), name='uniq_user_profiles_telegram_id'),
        ),
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='authorcode',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_author_codes', to='api.userprofile'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['user', 'status'], name='participati_user_id_02d1f0_idx'),
        ),
        migrations.AddIndex(
            model_name='authorcode',
            index=models.Index(fields=['code', 'active'], name='author_code_code_cfc63b_idx'),
        ),
    ]
