# Generated by Django 4.2.27 on 2026-01-01 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_authorcode_participation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='author_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='amount_usd_cents',
            field=models.IntegerField(default=3300),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='tx_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['referrer', 'status'], name='participati_referre_8c561e_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['referrer', 'created_at'], name='participati_referre_41b813_idx'),
        ),
    ]
