# Generated by Django 4.2.27 on 2026-01-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_participation_author_code_participation_referrer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('login', 'login'), ('connect', 'connect'), ('telegram_verify', 'telegram_verify'), ('apply_code', 'apply_code'), ('inviter_set', 'inviter_set'), ('payment_create', 'payment_create'), ('payment_confirm', 'payment_confirm'), ('intent_create', 'intent_create'), ('participation_confirm', 'participation_confirm'), ('payout_request', 'payout_request'), ('payout_mark', 'payout_mark')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='amount_usd_cents',
            field=models.IntegerField(default=100),
        ),
    ]
